In [74]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [75]:
"""
/content/drive/MyDrive/DA_DM_Project/NYPD_Complaint_Data_Current_(Year_To_Date)_20260126.csv
"""

'\n/content/drive/MyDrive/DA_DM_Project/NYPD_Complaint_Data_Current_(Year_To_Date)_20260126.csv\n'

In [76]:
import pandas as pd

file_path = "/content/drive/MyDrive/MCM/Sem2/CSC1144 Data Analytics & Data Mining/Project/NYPD_Complaint_Data_Current_(Year_To_Date)_20260126.csv"
df = pd.read_csv(file_path, low_memory=False)

print(df.shape)
df.head()

(438556, 36)

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,...,TRANSIT_DISTRICT,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column
0,303250435,13,MANHATTAN,03/20/2025,00:30:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,25-44,WHITE,M,988886,207857,40.737203,-73.983273,"(40.7372030985741, -73.9832725981497)",POINT (-73.9832725981497 40.7372030985741)
1,309137838,14,MANHATTAN,07/05/2025,18:00:00,07/05/2025,18:31:00,COMPLETED,(null),NaN,...,NaN,18-24,BLACK,F,0,0,0.000000,0.000000,"(0.0, 0.0)",POINT (0 0)
2,298788022,81,BROOKLYN,01/02/2025,01:50:00,01/02/2025,03:00:00,COMPLETED,(null),NaN,...,NaN,18-24,WHITE,F,1005319,190473,40.689464,-73.924029,"(40.6894642952604, -73.9240290899499)",POINT (-73.9240290899499 40.6894642952604)
3,307271594,47,BRONX,03/05/2025,17:00:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,25-44,BLACK,F,1026480,262584,40.887314,-73.847272,"(40.8873136344706, -73.8472717577564)",POINT (-73.8472717577564 40.8873136344706)
4,306868358,9,MANHATTAN,05/22/2025,14:30:00,05/22/2025,14:45:00,COMPLETED,(null),NaN,...,NaN,UNKNOWN,UNKNOWN,M,0,0,0.000000,0.000000,"(0.0, 0.0)",POINT (0 0)

In [77]:
df.columns

Index(['CMPLNT_NUM', 'ADDR_PCT_CD', 'BORO_NM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM',
       'CMPLNT_TO_DT', 'CMPLNT_TO_TM', 'CRM_ATPT_CPTD_CD', 'HADEVELOPT',
       'HOUSING_PSA', 'JURISDICTION_CODE', 'JURIS_DESC', 'KY_CD', 'LAW_CAT_CD',
       'LOC_OF_OCCUR_DESC', 'OFNS_DESC', 'PARKS_NM', 'PATROL_BORO', 'PD_CD',
       'PD_DESC', 'PREM_TYP_DESC', 'RPT_DT', 'STATION_NAME', 'SUSP_AGE_GROUP',
       'SUSP_RACE', 'SUSP_SEX', 'TRANSIT_DISTRICT', 'VIC_AGE_GROUP',
       'VIC_RACE', 'VIC_SEX', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude',
       'Longitude', 'Lat_Lon', 'New Georeferenced Column'],
      dtype='object')

In [78]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(438556, 36)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438556 entries, 0 to 438555
Data columns (total 36 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CMPLNT_NUM                438556 non-null  object
 1   ADDR_PCT_CD               438556 non-null  int64
 2   BORO_NM                   438556 non-null  object
 3   CMPLNT_FR_DT              438556 non-null  object
 4   CMPLNT_FR_TM              438556 non-null  object
 5   CMPLNT_TO_DT              418228 non-null  object
 6   CMPLNT_TO_TM              438556 non-null  object
 7   CRM_ATPT_CPTD_CD          438556 non-null  object
 8   HADEVELOPT                438556 non-null  object
 9   HOUSING_PSA               27186 non-null   float64
 10  JURISDICTION_CODE         438556 non-null  int64
 11  JURIS_DESC                438556 non-null  object
 12  KY_CD                     438556 non-null  int64
 13  LAW_CAT_CD                438556 non-null  object
 14  LOC_OF_OCCUR_DESC         438556 non-null  object
 15  OFNS_DESC                 438556 non-null  object
 16  PARKS_NM                  438556 non-null  object
 17  PATROL_BORO               438556 non-null  object
 18  PD_CD                     438313 non-null  float64
 19  PD_DESC                   438556 non-null  object
 20  PREM_TYP_DESC             438556 non-null  object
 21  RPT_DT                    438556 non-null  object
 22  STATION_NAME              438556 non-null  object
 23  SUSP_AGE_GROUP            438556 non-null  object
 24  SUSP_RACE                 438556 non-null  object
 25  SUSP_SEX                  438556 non-null  object
 26  TRANSIT_DISTRICT          26258 non-null   float64
 27  VIC_AGE_GROUP             438556 non-null  object
 28  VIC_RACE                  438556 non-null  object
 29  VIC_SEX                   438556 non-null  object
 30  X_COORD_CD                438556 non-null  int64
 31  Y_COORD_CD                438556 non-null  int64
 32  Latitude                  438556 non-null  float64
 33  Longitude                 438556 non-null  float64
 34  Lat_Lon                   438556 non-null  object
 35  New Georeferenced Column  438556 non-null  object
dtypes: float64(5), int64(5), object(26)
memory usage: 120.5+ MB
None
CMPLNT_NUM                       0
ADDR_PCT_CD                      0
BORO_NM                          0
CMPLNT_FR_DT                     0
CMPLNT_FR_TM                     0
CMPLNT_TO_DT                 20328
CMPLNT_TO_TM                     0
CRM_ATPT_CPTD_CD                 0
HADEVELOPT                       0
HOUSING_PSA                 411370
JURISDICTION_CODE                0
JURIS_DESC                       0
KY_CD                            0
LAW_CAT_CD                       0
LOC_OF_OCCUR_DESC                0
OFNS_DESC                        0
PARKS_NM                         0
PATROL_BORO                      0
PD_CD                          243
PD_DESC                          0
PREM_TYP_DESC                    0
RPT_DT                           0
STATION_NAME                     0
SUSP_AGE_GROUP                   0
SUSP_RACE                        0
SUSP_SEX                         0
TRANSIT_DISTRICT            412298
VIC_AGE_GROUP                    0
VIC_RACE                         0
VIC_SEX                          0
X_COORD_CD                       0
Y_COORD_CD                       0
Latitude                         0
Longitude                        0
Lat_Lon                          0
New Georeferenced Column         0
dtype: int64

In [79]:
missing = df.isna().sum().sort_values(ascending=False)
missing.head(20)

TRANSIT_DISTRICT     412298
HOUSING_PSA          411370
CMPLNT_TO_DT          20328
PD_CD                   243
CMPLNT_FR_DT              0
BORO_NM                   0
ADDR_PCT_CD               0
CMPLNT_NUM                0
CRM_ATPT_CPTD_CD          0
HADEVELOPT                0
JURISDICTION_CODE         0
CMPLNT_TO_TM              0
JURIS_DESC                0
KY_CD                     0
LOC_OF_OCCUR_DESC         0
LAW_CAT_CD                0
OFNS_DESC                 0
PARKS_NM                  0
PATROL_BORO               0
CMPLNT_FR_TM              0
dtype: int64

In [80]:
df["CMPLNT_FR_DT"] = pd.to_datetime(df["CMPLNT_FR_DT"], errors="coerce")
df["CMPLNT_TO_DT"] = pd.to_datetime(df["CMPLNT_TO_DT"], errors="coerce")

In [81]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438556 entries, 0 to 438555
Data columns (total 36 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CMPLNT_NUM                438556 non-null  object
 1   ADDR_PCT_CD               438556 non-null  int64
 2   BORO_NM                   438556 non-null  object
 3   CMPLNT_FR_DT              438551 non-null  datetime64[ns]
 4   CMPLNT_FR_TM              438556 non-null  object
 5   CMPLNT_TO_DT              418228 non-null  datetime64[ns]
 6   CMPLNT_TO_TM              438556 non-null  object
 7   CRM_ATPT_CPTD_CD          438556 non-null  object
 8   HADEVELOPT                438556 non-null  object
 9   HOUSING_PSA               27186 non-null   float64
 10  JURISDICTION_CODE         438556 non-null  int64
 11  JURIS_DESC                438556 non-null  object
 12  KY_CD                     438556 non-null  int64
 13  LAW_CAT_CD                438556 non-null  object
 14  LOC_OF_OCCUR_DESC         438556 non-null  object
 15  OFNS_DESC                 438556 non-null  object
 16  PARKS_NM                  438556 non-null  object
 17  PATROL_BORO               438556 non-null  object
 18  PD_CD                     438313 non-null  float64
 19  PD_DESC                   438556 non-null  object
 20  PREM_TYP_DESC             438556 non-null  object
 21  RPT_DT                    438556 non-null  object
 22  STATION_NAME              438556 non-null  object
 23  SUSP_AGE_GROUP            438556 non-null  object
 24  SUSP_RACE                 438556 non-null  object
 25  SUSP_SEX                  438556 non-null  object
 26  TRANSIT_DISTRICT          26258 non-null   float64
 27  VIC_AGE_GROUP             438556 non-null  object
 28  VIC_RACE                  438556 non-null  object
 29  VIC_SEX                   438556 non-null  object
 30  X_COORD_CD                438556 non-null  int64
 31  Y_COORD_CD                438556 non-null  int64
 32  Latitude                  438556 non-null  float64
 33  Longitude                 438556 non-null  float64
 34  Lat_Lon                   438556 non-null  object
 35  New Georeferenced Column  438556 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(5), object(24)
memory usage: 120.5+ MB
None

In [82]:
missing = df.isna().sum().sort_values(ascending=False)
missing.head(20)

TRANSIT_DISTRICT     412298
HOUSING_PSA          411370
CMPLNT_TO_DT          20328
PD_CD                   243
CMPLNT_FR_DT              5
BORO_NM                   0
CMPLNT_NUM                0
ADDR_PCT_CD               0
CRM_ATPT_CPTD_CD          0
HADEVELOPT                0
JURISDICTION_CODE         0
CMPLNT_TO_TM              0
JURIS_DESC                0
KY_CD                     0
LOC_OF_OCCUR_DESC         0
LAW_CAT_CD                0
OFNS_DESC                 0
PARKS_NM                  0
PATROL_BORO               0
CMPLNT_FR_TM              0
dtype: int64

In [83]:
df["CMPLNT_FR_TM"] = pd.to_datetime(df["CMPLNT_FR_TM"], errors="coerce").dt.time
df["CMPLNT_TO_TM"] = pd.to_datetime(df["CMPLNT_TO_TM"], errors="coerce").dt.time

/tmp/ipython-input-2129986211.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["CMPLNT_FR_TM"] = pd.to_datetime(df["CMPLNT_FR_TM"], errors="coerce").dt.time
/tmp/ipython-input-2129986211.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["CMPLNT_TO_TM"] = pd.to_datetime(df["CMPLNT_TO_TM"], errors="coerce").dt.time

In [84]:
missing = df.isna().sum().sort_values(ascending=False)
missing.head(20)

TRANSIT_DISTRICT     412298
HOUSING_PSA          411370
CMPLNT_TO_DT          20328
CMPLNT_TO_TM          20001
PD_CD                   243
CMPLNT_FR_DT              5
CMPLNT_NUM                0
ADDR_PCT_CD               0
BORO_NM                   0
CRM_ATPT_CPTD_CD          0
JURISDICTION_CODE         0
HADEVELOPT                0
JURIS_DESC                0
KY_CD                     0
LOC_OF_OCCUR_DESC         0
LAW_CAT_CD                0
OFNS_DESC                 0
PARKS_NM                  0
PATROL_BORO               0
CMPLNT_FR_TM              0
dtype: int64

In [85]:
df.shape

(438556, 36)

In [86]:
# Count duplicates
df.duplicated().sum()

# Remove duplicates
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (438556, 36)

No duplicates

In [87]:
df["BORO_NM"].unique()

array(['MANHATTAN', 'BROOKLYN', 'BRONX', 'STATEN ISLAND', 'QUEENS',
       '(null)'], dtype=object)

In [88]:
# Ensure numeric
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

# Impossible coordinates mask
invalid_coords = (
    (df["Latitude"] < 40) | (df["Latitude"] > 42) |
    (df["Longitude"] < -75) | (df["Longitude"] > -72)
)

# Count
num_invalid = invalid_coords.sum()

print("Number of impossible coordinates:", num_invalid)

Number of impossible coordinates: 2906

In [89]:
# Remove invalid lat/long if present
if "Latitude" in df.columns:
    df = df[(df["Latitude"].between(40, 42))]

if "Longitude" in df.columns:
    df = df[(df["Longitude"].between(-75, -72))]

In [90]:
df.shape

(435650, 36)

In [91]:
# Create Consistent Time Features
df["year"] = df["CMPLNT_FR_DT"].dt.year.astype("Int64")
df["month"] = df["CMPLNT_FR_DT"].dt.month.astype("Int64")
df["day"] = df["CMPLNT_FR_DT"].dt.day.astype("Int64")
df["day_of_week"] = df["CMPLNT_FR_DT"].dt.day_name()

In [92]:
df.head()

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,...,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column,year,month,day,day_of_week
0,303250435,13,MANHATTAN,2025-03-20,00:30:00,NaT,NaT,COMPLETED,(null),NaN,...,988886,207857,40.737203,-73.983273,"(40.7372030985741, -73.9832725981497)",POINT (-73.9832725981497 40.7372030985741),2025,3,20,Thursday
2,298788022,81,BROOKLYN,2025-01-02,01:50:00,2025-01-02,03:00:00,COMPLETED,(null),NaN,...,1005319,190473,40.689464,-73.924029,"(40.6894642952604, -73.9240290899499)",POINT (-73.9240290899499 40.6894642952604),2025,1,2,Thursday
3,307271594,47,BRONX,2025-03-05,17:00:00,NaT,NaT,COMPLETED,(null),NaN,...,1026480,262584,40.887314,-73.847272,"(40.8873136344706, -73.8472717577564)",POINT (-73.8472717577564 40.8873136344706),2025,3,5,Wednesday
5,299744592,121,STATEN ISLAND,2025-01-20,18:30:00,2025-01-20,18:35:00,COMPLETED,(null),NaN,...,938881,167697,40.626859,-74.163440,"(40.626859, -74.16344)",POINT (-74.16344 40.626859),2025,1,20,Monday
6,309582473,121,STATEN ISLAND,2025-07-12,20:45:00,2025-07-12,21:00:00,COMPLETED,(null),NaN,...,944834,161146,40.608906,-74.141958,"(40.608906, -74.141958)",POINT (-74.141958 40.608906),2025,7,12,Saturday

In [93]:
# Inconsistent Complaint Dates
if "CMPLNT_TO_DT" in df.columns:
    duration = (df["CMPLNT_TO_DT"] - df["CMPLNT_FR_DT"]).dt.days

    inconsistent_mask = duration < 0

    print("Records with inconsistent complaint dates:", inconsistent_mask.sum())

    # Drop inconsistent records
    df = df[~inconsistent_mask]

    print("Remaining rows after removal:", df.shape[0])

Records with inconsistent complaint dates: 4
Remaining rows after removal: 435646

In [94]:
# Remove irrelevant columns
df = df.drop(columns=["TRANSIT_DISTRICT", "HOUSING_PSA", "PD_CD", "CMPLNT_TO_DT", "CMPLNT_TO_TM"])

In [95]:
# Removing rows with missing values in key attributes (borough, offense description, complaint date)before = df.shape[0]

df = df.dropna(subset=["BORO_NM", "OFNS_DESC", "CMPLNT_FR_DT"])

after = df.shape[0]

print("Rows dropped:", before - after)
print("Remaining rows:", after)

Rows dropped: 5
Remaining rows: 435641